services:
  redis:
    image: redis:7-alpine
    container_name: chess-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

networks:
  default:
    name: chess-network

volumes:
  redis_data:
